[package]
name = "ftp-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ftp-server"
path = "src/main.rs"

[dependencies]
libunftp = { path = "libunftp-patched", default-features = false, features = ["ring"] }
unftp-core = "0.1.0"
tokio = { version = "1", features = ["full"] }
toml = "0.8"
serde = { version = "1", features = ["derive"] }
async-trait = "0.1"
bytes = "1"
